import { useEffect, useState, type CSSProperties, type ReactNode } from 'react';
import { AbsoluteFill, Audio, Composition, continueRender, delayRender, Easing, interpolate, staticFile, useCurrentFrame } from 'remotion';
import data from '../src/data/fonts.json';
import music from './music.wav'; // generated by video/music.py

// 20s kinetic-type showreel at 120 BPM: every cut and hit sits on the 0.5s beat grid shared with video/music.py.
const FPS = 60, SECONDS = 20;
const FONTS = data.fonts.map(f => f.id);
const WINNER = 'victor-mono';
const INK = '#0b0b0a', LIME = '#c6ff3d', PAPER = '#f1f0e8', HOT = '#ff4d1f', VIOLET = '#9d8cff';
const OUT = Easing.bezier(0.16, 1, 0.3, 1), IN_OUT = Easing.bezier(0.83, 0, 0.17, 1), IN = Easing.bezier(0.7, 0, 0.84, 0), POP = Easing.bezier(0.34, 1.56, 0.64, 1);

const k = (t: number, a: number, b: number, from: number, to: number, easing = OUT) =>
  interpolate(t, [a, b], [from, to], { easing, extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
const ff = (id: string) => `"ad-${id}", monospace`;
/** Slot-machine font: cycles through all 16, then lands on `target` at `settle`. */
const slot = (t: number, settle: number, target: string, seed = 0, rate = 22) =>
  t >= settle ? target : FONTS[(Math.floor(t * rate) + seed) % FONTS.length];

function useFonts() {
  const [handle] = useState(() => delayRender('Loading fonts'));
  const [ready, setReady] = useState(false);
  useEffect(() => {
    Promise.all(data.fonts.map(f => new FontFace(`ad-${f.id}`, `url(${staticFile(f.file)})`).load().then(face => document.fonts.add(face))))
      .then(() => { setReady(true); continueRender(handle); });
  }, [handle]);
  return ready;
}

/** Masked slide-up reveal, with an optional slide-up exit. */
function Reveal({ t, at, exit = 99, children, style }: {t: number; at: number; exit?: number; children: ReactNode; style?: CSSProperties}) {
  const y = (1 - k(t, at, at + 0.5, 0, 1)) * 110 - k(t, exit, exit + 0.3, 0, 1, IN) * 110;
  return <span style={{ display: 'inline-block', overflow: 'hidden', verticalAlign: 'bottom', paddingBottom: '0.08em', ...style }}>
    <span style={{ display: 'inline-block', transform: `translateY(${y}%)` }}>{children}</span>
  </span>;
}

// 0–1.0s: a terminal cursor blinks, then stretches into a lime field.
function Cursor({ t }: {t: number}) {
  const w = k(t, 0.5, 0.75, 36, 1920, IN_OUT), h = k(t, 0.75, 1.0, 72, 1080, IN_OUT);
  const on = t >= 0.5 || Math.floor(t / 0.25) % 2 === 0;
  return <AbsoluteFill style={{ background: INK, alignItems: 'center', justifyContent: 'center' }}>
    {on && <div style={{ width: w, height: h, background: LIME }} />}
  </AbsoluteFill>;
}

// 1.0–3.5s: an endless, tilted wall of "Aa" in every font; the caption slams in as tape labels.
function Wall({ t }: {t: number}) {
  const zoom = k(t, 1.0, 3.5, 1.35, 1.0, Easing.out(Easing.cubic));
  const tile = 230, loop = tile * FONTS.length;
  const words: [string, number][][] = [[['So', 1.25], ['many', 1.5]], [['terminal', 1.75], ['fonts.', 2.0]]];
  return <AbsoluteFill style={{ background: LIME, overflow: 'hidden' }}>
    <div style={{ position: 'absolute', left: -500, top: -560, width: 2920, transform: `rotate(-8deg) scale(${zoom})` }}>
      {Array.from({ length: 10 }, (_, r) => {
        const off = (((t * (240 + r * 45) * (r % 2 ? 1 : -1)) % loop) + loop) % loop;
        return <div key={r} style={{ display: 'flex', height: tile, transform: `translateX(${-off}px)` }}>
          {Array.from({ length: 40 }, (_, i) => <div key={i} style={{ flex: 'none', width: tile, textAlign: 'center', lineHeight: `${tile}px`, fontSize: 150, color: INK, opacity: 0.88, fontFamily: ff(FONTS[(i + r * 5) % FONTS.length]) }}>Aa</div>)}
        </div>;
      })}
    </div>
    <AbsoluteFill style={{ alignItems: 'center', justifyContent: 'center', gap: 22, transform: 'rotate(-8deg)' }}>
      {words.map((line, li) => <div key={li} style={{ display: 'flex', gap: 26 }}>
        {line.map(([w, at], i) => {
          const p = k(t, at, at + 0.45, 0, 1, POP);
          return <span key={w} style={{ display: 'inline-block', background: INK, color: PAPER, padding: '4px 34px 16px', fontSize: 150, lineHeight: 1, transform: `scale(${p}) rotate(${(1 - p) * -14}deg)` }}>
            {[...w].map((c, j) => <span key={j} style={{ fontFamily: ff(FONTS[(li * 11 + i * 5 + j * 7) % FONTS.length]) }}>{c}</span>)}
          </span>;
        })}
      </div>)}
    </AbsoluteFill>
  </AbsoluteFill>;
}

// 3.25–5.0s: circle wipe to black; the question rises word by word over a giant spinning "?".
function Question({ t }: {t: number}) {
  const r = k(t, 3.25, 3.5, 0, 1200, IN_OUT);
  const words: [string, number][] = [['How', 3.5], ['do', 3.625], ['you', 3.75], ['pick', 3.875], ['one?', 4.0]];
  return <AbsoluteFill style={{ background: INK, clipPath: `circle(${r}px at 50% 50%)`, alignItems: 'center', justifyContent: 'center' }}>
    <div style={{ position: 'absolute', fontSize: 1000, lineHeight: 1, color: 'transparent', WebkitTextStroke: '3px #33372f', fontFamily: ff(slot(t, 99, WINNER, 0, 6)), transform: `rotate(${k(t, 3.25, 5.0, -12, 12, Easing.linear)}deg) scale(${k(t, 3.25, 5.0, 1.15, 0.95, Easing.linear)})` }}>?</div>
    <div style={{ display: 'flex', gap: 34, fontSize: 124, color: PAPER, fontFamily: ff(WINNER) }}>
      {words.map(([w, at]) => <Reveal key={w} t={t} at={at} style={w === 'one?' ? { color: LIME, fontFamily: ff(slot(t, 4.5, WINNER, 5)) } : undefined}>{w}</Reveal>)}
    </div>
  </AbsoluteFill>;
}

// 4.75–10.0s: split-screen duels, faster every round. The loser is wiped away, a challenger pushes in.
const ROUNDS = [
  { a: 5.0, b: 7.0, L: 'hack', R: 'mononoki', win: 'L' },
  { a: 7.0, b: 8.5, L: 'hack', R: WINNER, win: 'R' },
  { a: 8.5, b: 9.5, L: 'iosevka', R: WINNER, win: 'R' },
  { a: 9.5, b: 10.0, L: 'fira-code', R: WINNER, win: 'R' },
] as const;
const COLOR: Record<string, string> = { hack: PAPER, mononoki: HOT, iosevka: VIOLET, 'fira-code': HOT, [WINNER]: LIME };
const phase = (r: typeof ROUNDS[number]) => { const d = r.b - r.a; return { press: r.a + 0.5 * d, cut: r.a + 0.55 * d, gone: r.a + 0.75 * d, back: r.a + 0.8 * d }; };

/** Left panel width (%) and the two fonts on screen at time t. */
function duel(t: number) {
  const found = ROUNDS.findIndex(r => t < r.b);
  const i = found === -1 ? ROUNDS.length - 1 : found;
  const r = ROUNDS[i], p = phase(r), next = ROUNDS[i + 1];
  const winW = r.win === 'L' ? 100 : 0;
  let w = 50;
  if (t >= p.cut) w = k(t, p.cut, p.gone, 50, winW, IN_OUT);
  if (next && t >= p.back) w = k(t, p.back, r.b, winW, 50, OUT);
  const swapped = next && t >= p.gone;
  return { w, L: swapped ? next.L : r.L, R: swapped ? next.R : r.R };
}

function Keycap({ arrow, press }: {arrow: string; press: number}) {
  return <div style={{ width: 150, height: 130, borderRadius: 24, background: '#161715', color: LIME, fontSize: 84, lineHeight: '124px', textAlign: 'center', fontFamily: ff(WINNER),
    transform: `translateY(${press * 12}px)`, boxShadow: `0 ${16 - 12 * press}px 0 #000, 0 ${30 - 18 * press}px 50px rgba(0,0,0,.45)`, border: '2px solid #2a2c28' }}>{arrow}</div>;
}

function Duels({ t }: {t: number}) {
  const { w, L, R } = duel(t);
  const pressOf = (side: 'L' | 'R') => ROUNDS.reduce((sum, r) => {
    const p = phase(r);
    if (r.win !== side || t < p.press - 0.08 || t >= p.cut + 0.1) return sum;
    return sum + (t < p.press ? k(t, p.press - 0.08, p.press, 0, 1) : k(t, p.cut, p.cut + 0.1, 1, 0));
  }, 0);
  const hit = ROUNDS.map(r => phase(r).press).filter(p => t >= p).pop();
  const since = hit === undefined ? 9 : t - hit;
  const shake = 14 * Math.sin(since * 70) * Math.exp(-since * 14);
  const flash = hit === undefined ? 0 : 0.35 * Math.exp(-since * 18);
  const enter = k(t, 4.75, 5.0, 100, 0, IN_OUT);
  const keysY = k(t, 5.0, 5.35, 300, 0, POP) + k(t, 9.8, 10.0, 0, 300, IN);
  const picks = ROUNDS.map(r => phase(r).press).filter(p => t >= p);
  const count = [16, 8, 4, 2, 1][picks.length];
  const roll = picks.length ? k(t, picks[picks.length - 1], picks[picks.length - 1] + 0.3, 100, 0) : 0;
  const panel = (font: string, width: number, from: number): CSSProperties => ({ position: 'relative', width: `${width}%`, height: '100%', overflow: 'hidden', background: COLOR[font], transform: `translateY(${from * enter}%)` });
  const glyph: CSSProperties = { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 380, color: INK, lineHeight: 1, paddingBottom: 60 };
  return <AbsoluteFill style={{ background: INK }}>
    <AbsoluteFill style={{ flexDirection: 'row', transform: `translateX(${shake}px)` }}>
      <div style={panel(L, w, -1)}><div style={{ ...glyph, fontFamily: ff(L) }}>Aa</div></div>
      <div style={panel(R, 100 - w, 1)}><div style={{ ...glyph, fontFamily: ff(R) }}>Aa</div></div>
    </AbsoluteFill>
    <AbsoluteFill style={{ top: 120, fontSize: 104, color: INK, fontFamily: ff(WINNER) }}>
      <div style={{ position: 'absolute', width: '50%', textAlign: 'center' }}><Reveal t={t} at={5.1} exit={5.55}>Left</Reveal></div>
      <div style={{ position: 'absolute', left: 0, right: 0, textAlign: 'center' }}><Reveal t={t} at={5.18} exit={5.55}><span style={{ color: PAPER, background: INK, padding: '0 22px' }}>or</span></Reveal></div>
      <div style={{ position: 'absolute', left: '50%', width: '50%', textAlign: 'center' }}><Reveal t={t} at={5.26} exit={5.55}>right?</Reveal></div>
    </AbsoluteFill>
    <div style={{ position: 'absolute', right: 56, top: 44, textAlign: 'right', color: INK, fontFamily: ff(WINNER), opacity: t > 5.0 && t < 9.9 ? 1 : 0 }}>
      <div style={{ fontSize: 96, lineHeight: 1, overflow: 'hidden', fontVariantNumeric: 'tabular-nums' }}><div style={{ transform: `translateY(${roll}%)` }}>{String(count).padStart(2, '0')}</div></div>
      <div style={{ fontSize: 26, letterSpacing: 2 }}>FONTS LEFT</div>
    </div>
    <div style={{ position: 'absolute', bottom: 70, left: 0, right: 0, display: 'flex', justifyContent: 'center', gap: 28, transform: `translateY(${keysY}px)` }}>
      <Keycap arrow="←" press={pressOf('L')} /><Keycap arrow="→" press={pressOf('R')} />
    </div>
    <AbsoluteFill style={{ background: '#fff', opacity: flash }} />
  </AbsoluteFill>;
}

// 10.0–12.0s: zoom through the winner's "a" into black; the payoff lines rise.
function Payoff({ t }: {t: number}) {
  const origin = 'calc(50% + 150px) calc(50% - 10px)';
  const s = k(t, 10.0, 10.5, 1, 28, IN);
  const hole = k(t, 10.3, 10.5, 0, 1400, IN_OUT);
  return <AbsoluteFill style={{ background: LIME }}>
    <AbsoluteFill style={{ alignItems: 'center', justifyContent: 'center', paddingBottom: 60, fontSize: 380, lineHeight: 1, color: INK, fontFamily: ff(WINNER), transform: `scale(${s})`, transformOrigin: origin }}>Aa</AbsoluteFill>
    <AbsoluteFill style={{ background: INK, clipPath: `circle(${hole}px at ${origin})` }} />
    <AbsoluteFill style={{ alignItems: 'center', justifyContent: 'center', gap: 10, fontSize: 140, fontFamily: ff(WINNER) }}>
      <Reveal t={t} at={10.5} exit={11.72} style={{ color: PAPER }}>Pick by eye.</Reveal>
      <Reveal t={t} at={11.0} exit={11.78} style={{ color: LIME }}>Find your font.</Reveal>
    </AbsoluteFill>
  </AbsoluteFill>;
}

// 12.0–20.0s: the title assembles from every font into the winner; then back to a lone cursor, which loops.
function EndCard({ t }: {t: number}) {
  const title = 'Terminal Font Duel';
  const exit = 19.45;
  const cursorOn = t >= 19.75 && Math.floor((t - 19.75) / 0.25) % 2 === 0;
  return <AbsoluteFill style={{ background: INK, alignItems: 'center', justifyContent: 'center' }}>
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 26, opacity: k(t, exit, exit + 0.3, 1, 0, IN) }}>
      <div style={{ position: 'relative', fontSize: 150, lineHeight: 1.1, color: PAPER, whiteSpace: 'pre' }}>
        {[...title].map((c, i) => {
          const at = 12.05 + i * 0.035, p = k(t, at, at + 0.4, 0, 1);
          return <span key={i} style={{ display: 'inline-block', fontFamily: ff(slot(t, at + 0.45, WINNER, i)), opacity: p, transform: `translateY(${(1 - p) * 50}px)` }}>{c}</span>;
        })}
        <div style={{ height: 10, background: LIME, marginTop: 8, transformOrigin: 'left', transform: `scaleX(${k(t, 12.8, 13.25, 0, 1, IN_OUT)})` }} />
      </div>
      <Reveal t={t} at={13.0} style={{ fontSize: 50, color: PAPER, fontFamily: ff(WINNER) }}>Find your favorite terminal font by gut feel.</Reveal>
      <Reveal t={t} at={13.25} style={{ fontSize: 28, color: '#8d8f86', fontFamily: ff(WINNER), letterSpacing: 1 }}>16 Nerd Fonts · all installable with Homebrew · terminal-font-duel.muehl.io</Reveal>
    </div>
    {cursorOn && <div style={{ position: 'absolute', width: 36, height: 72, background: LIME }} />}
  </AbsoluteFill>;
}

function Grain({ frame }: {frame: number}) {
  return <AbsoluteFill style={{ pointerEvents: 'none', mixBlendMode: 'overlay', opacity: 0.12 }}>
    <svg width="100%" height="100%"><filter id="grain"><feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves={2} seed={frame % 12} /></filter><rect width="100%" height="100%" filter="url(#grain)" /></svg>
  </AbsoluteFill>;
}

export function Ad() {
  const frame = useCurrentFrame();
  const t = frame / FPS;
  if (!useFonts()) return null;
  return <AbsoluteFill style={{ background: INK }}>
    <Audio src={music} />
    {t < 1.0 && <Cursor t={t} />}
    {t >= 1.0 && t < 3.5 && <Wall t={t} />}
    {t >= 3.25 && t < 5.0 && <Question t={t} />}
    {t >= 4.75 && t < 10.0 && <Duels t={t} />}
    {t >= 10.0 && t < 12.0 && <Payoff t={t} />}
    {t >= 12.0 && <EndCard t={t} />}
    <Grain frame={frame} />
    <AbsoluteFill style={{ pointerEvents: 'none', background: 'radial-gradient(ellipse at center, transparent 55%, rgba(0,0,0,.35) 100%)' }} />
  </AbsoluteFill>;
}

export const Root = () => <Composition id="Ad" component={Ad} fps={FPS} durationInFrames={SECONDS * FPS} width={1920} height={1080} />;
